### ISSUE TITLE
CLI Arguments

### ISSUE THREAD

**Issue by NicktheGeek** [mghoneimy/php-graphql-oqm#32]
The object generation script does not accept arguments, which requires an interactive prompt. In environments where vendor directory is not included in the repo, but are built for deploy, it is impossible to generate in the build process.

While a custom write directory can be created and committed, there are additional benefits to allowing CLI arguments instead of the interactive command such as sharing commands between team members or simply bypassing the interactive prompt entirely.

**Comment by mghoneimy** [comment]
addressed by #28
